// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1alpha1

// SnapshotListerExpansion allows custom methods to be added to
// SnapshotLister.
type SnapshotListerExpansion interface{}

// SnapshotNamespaceListerExpansion allows custom methods to be added to
// SnapshotNamespaceLister.
type SnapshotNamespaceListerExpansion interface{}
