// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	avav1alpha1 "github.com/qiniu-ava/snapshot-operator/pkg/apis/ava/v1alpha1"
	versioned "github.com/qiniu-ava/snapshot-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/qiniu-ava/snapshot-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/qiniu-ava/snapshot-operator/pkg/client/listers/ava/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotInformer provides access to a shared informer and lister for
// Snapshots.
type SnapshotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SnapshotLister
}

type snapshotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSnapshotInformer constructs a new informer for Snapshot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSnapshotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSnapshotInformer constructs a new informer for Snapshot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnapshotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AvaV1alpha1().Snapshots(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AvaV1alpha1().Snapshots(namespace).Watch(options)
			},
		},
		&avav1alpha1.Snapshot{},
		resyncPeriod,
		indexers,
	)
}

func (f *snapshotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSnapshotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *snapshotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&avav1alpha1.Snapshot{}, f.defaultInformer)
}

func (f *snapshotInformer) Lister() v1alpha1.SnapshotLister {
	return v1alpha1.NewSnapshotLister(f.Informer().GetIndexer())
}
