// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/qiniu-ava/snapshot-operator/pkg/client/clientset/versioned/typed/ava/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAvaV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAvaV1alpha1) Snapshots(namespace string) v1alpha1.SnapshotInterface {
	return &FakeSnapshots{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAvaV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
